### ISSUE TITLE
Elargir les zones de textes

### ISSUE THREAD

**Issue by Karim-PBC** [FrancoisGuillem/pbf#11]
Possibilité sur la page d'accueil et toutes les autres d’élargir la zone de texte pour éviter qu’il soit trop gros et force à scroller ?

exemple page d'accueil avec le texte : 

"Rendez-vous du 3 au 9 octobre 2020 pour célébrer la bière artisanale et indépendante dans tout Paris et en Île-de-France et les 10 et 11 octobre à Ground Control pour un week-end de clôture avec près de 40 microbrasseries locales et nationales !"

**Comment by enwin** [comment]
✅
