### ISSUE TITLE
Retirer la section "paris beer festival" sur la page Paris Beer Club

### ISSUE THREAD

**Issue by Karim-PBC** [FrancoisGuillem/pbf#13]
Enlever la partie “Paris Beer Festival”en bas de  cette page qui fait doublon avec la catégorie qu’on aimerait créée + la page d’accueil :

Section jaune sur cette partie :
https://parisbeerfestival.fr/fr/a-propos/lassociation-paris-beer-club/

**Comment by enwin** [comment]
✅
