### ISSUE TITLE
Lien en savoir plus

### ISSUE THREAD

**Issue by Karim-PBC** [FrancoisGuillem/pbf#8]
Sur la page d'accueil, dans la rubrique "Organisé par le Paris Beer Club"

Le lien "En savoir plus" doit ouvrir :
- soit la page "Paris Beer Club" prévue dans le menu "à propos"
- soit dans un nouvel onglet le site du Paris Beer Club.

**Comment by enwin** [comment]
Le lien est configuré pour ouvrir https://www.parisbeerclub.fr dans un nouvel onglet. Il y a un bug dans la génération du html qui fait que le lien ne fonctionne pas actuellement. Ce sera corrigé au prochain déploiement

**Comment by enwin** [comment]
✅
