### ISSUE TITLE
Page d'accueil - l'encart avec les 3 options

### ISSUE THREAD

**Issue by Karim-PBC** [FrancoisGuillem/pbf#9]
En dessous de la section "La paris beer week devient"... et au-dessous de la section "Organisé par le paris beer club" sur la page d'accueil ... il manque la section avec les 3 parties.

De plus, la troisième partie "Grand Final" doit s'appeler "Ground Control".

**Comment by enwin** [comment]
J'ai remis la liste des 3 parties. Par contre les textes dans la liste sont:

- Au programme
- Participants
- Infos Pratiques

Est-ce que je renomme Infos Pratiques en "Ground Control" ?

**Comment by Karim-PBC** [comment]
yes ! on remplace "Infos Pratiques" par "Ground Control" ;)

**Comment by enwin** [comment]
✅
